fix: Docker build
AlbertaSat/ex2_services pull request #24
Opened 2020-10-03 07:03 UTC by TheCandianVendingMachine

## [Clickup Task](app.clickup.com)(if applicable)

## Description of changes
f66d531285219d4b848ae964f79e3aa0e3e6af19 caused compilation errors for me building the demo app. I tracked it down to `SYSTEM_APP_ID` not being defined the entire time. The simple fix is to define the macro as a GCC argument so that it is guaranteed to be defined during the build, but when someone wants to fix the core issue at hand I added `system_header.h` to ensure that the value is always defined and that it will include the correct header every time when including the wanted system header.

## Testing done
* Docker now compiles project while previously it error'd out.
* I am able to send commands between the simulated ground station and services so nothing seems to be wrong there

## Merge checklist
- [ ] Docker image or CCS Project builds with the changes
- [ ] Docker image or CCS Project runs with the changes
- [ ] Can send commands from a mocked ground station/relevant changes tested
- [ ] Changes have been reviewed

2020-10-03 07:05 UTC, TheCandianVendingMachine commented
When looking through files I saw a few more `#include "system.h"` scattered about. I don't know if these are meant to be that way, or if we should change them. The relevant files are `communication_service.h` and `time_management_service.c`

2020-10-04 16:46 UTC, arrooney commented
nice, I'll try running this on the hardware to see if it'll work properly in the IDE. It uses a different compiler but hopefully this'll work!

2020-10-04 17:17 UTC, arrooney commented
https://github.com/AlbertaSat/ex2_obc_software/pull/3

2020-10-04 17:19 UTC, arrooney requested changes

2020-10-04 17:19 UTC, arrooney commented on Services/system_header.h
> +#endif
Just add an include guard. Otherwise LGTM

2020-10-04 19:27 UTC, arrooney approved these changes

2020-10-04 19:28 UTC, merged